services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    working_dir: /root/build/src
    environment:
      - SHELL=/bin/sh
    volumes:
      - ..:/root/build:cached